#!/bin/env sh

case "$(uname -s)" in
  MINGW*|MSYS*|CYGWIN*)
    powershell.exe -NoProfile -Command "npm run lint:commit -- --edit '$1'"
    ;;
  *)
    npm run lint:commit -- --edit "$1"
    ;;
esac
